# --- Main Colors ---
background            #16130b
foreground            #eae1d4
cursor                #eae1d4
cursor_text_color     #16130b

selection_background  #51462a
selection_foreground  #f3e1bb

url_color             #aecfac

# --- ANSI Colors ---
color0                #16130b
color1                #ffb4ab
color2                #aecfac
color3                #d6c5a0
color4                #e5c36c
color5                #aecfac
color6                #d6c5a0
color7                #eae1d4

color8                #4c4639
color9                #93000a
color10               #314d33
color11               #51462a
color12               #594400
color13               #51462a
color14               #314d33
color15               #cfc5b4

# --- Starship Prompt Bubbles ---
color255              #594400
color254              #e5c36c
color253              #51462a
color252              #d6c5a0
color251              #314d33
color250              #aecfac
color249              #93000a
color248              #ffb4ab

color232              #ffdf94
color233              #3e2e00
color234              #f3e1bb
color235              #392f15
color236              #caebc7
color237              #1b361e
color238              #ffdad6
color239              #690005
color240              #ffdf94

# Matched with unthemed light/dark
color243              #e5c36c
color244              #ffb4ab
color245              #4c4639

# --- UI Elements ---
active_tab_foreground   #3e2e00
active_tab_background   #e5c36c
inactive_tab_foreground #ffdf94
inactive_tab_background #594400

active_border_color     #e5c36c
inactive_border_color   #989080

# --- Marks ---
mark1_foreground        #241a00
mark1_background        #ffdf94
mark2_foreground        #231a04
mark2_background        #f3e1bb
mark3_foreground        #05210a
mark3_background        #caebc7
